### ISSUE TITLE
Components: too tightly coupled to dependencies

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/design-system#1079]
When using any components, there is no flexibility to use without adding multiple PS packages for styling.

### Expected behavior
With BC's in mind, the components should be as agnostic and lightweight as possible, not requiring or adding a CSS-in-JS library to the depedancy list, but rather using plain CSS. Essentally, a BC should not be required to install core, glamour, or any other dependency, but just download Dropdown and everything works fine.

### Actual behavior
If I only need to use `Dropdown` for example, I cannot just install the single package. It requires the installation of:
* core
* ActionMenu
* glamour
* also adds emotion to bundle

### Steps to repro

1. Create a new app using CRA w/ Typescript
2. Install styled-components (example)
2. Install `core` package
3. Install `Dropdown` & `ActionMenu`
4. Run tests (will fail due to no glamour)
5. Run bundle analyze to see emotion is added to bundle
6. Run start to see TS fails due to no typing packages (also no notes on this in the docs)

### Related packages
- core@latest
- Dropdown@latest
- ActionMenu@latest

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

### The Value Add

This allows the PSDS to be more flexible and keep all BC bundles as small as possible.

### The Tradeoffs

Requires possible rebuild to remove CSS-in-JS lib for pure CSS

**Comment by jaketrent** [comment]
Casey, thanks for the suggestion.

As I understand it, you're looking for:
- Simple install -- just the DS component package, no peerDeps
- Small js bundle size -- no css-in-js runtime

And as a tradeoff, you're wanting to:
- Configure your bundler to bundle DS vanilla CSS into your own stylesheet

Do I have that right?  What have I left out?

**Comment by jaketrent** [comment]
I'm surprised by the `emotion` dependency in the app js bundle.

Looking for it:

```
cd ~/design-system/packages && ag emotion **/package.json
```

I only find emotion in the storybook addons as a dependency, and I assume those are all devDeps.

**Comment by caseybaggz** [comment]
@jaketrent yeah, if I *really* think about this, I feel like the library should handle the webpack bundling and should just ship everything that is minimized and all, so all the engineer needs to worry about is importing and not getting additional weight with it? So if that means using plain CSS or just straight up CSS-in-JS via React (not using an additional lib), then so be it. Whatever needs to happen to keep it as light-weight and dependent free as possible.

Whatever **prevents**:
1. Requiring additional dependencies (I shouldn't have to add `core`, `ActionMenu`, etc., to use whatever component)
2. Requiring additional CSS-in-JS lib installation (I shouldn't have to install glamour in my app)
3. Preventing additional CSS-in-JS devDependency being installed into the app's bundle that consumes said components (components shouldn't bloat my app)

Does that make sense?

**Comment by caseybaggz** [comment]
Another good example of this is that the entire PSDS should be like a set of Legos, not a car. In order to use a car, I need a key, gas (or power if electric), and all the other parts working.

With Legos, you can build anything by combining any of the bricks in whatever way you fashion. It doesn't matter what you use - it will work just fine.

You can still *recommend* what bricks to combine in the docs - but it shouldn't be a requirement when implementing it.

**Comment by jaketrent** [comment]
Hey @caseybaggz , thanks for the perspective.  I'll share a few thoughts that may help as well:

- Packages do have peerDependencies in the case of runtime libraries (eg, react) or packages that must have a single instance in app bundles (eg, glamor, @pluralsight/ps-design-system-theme) or baselines upon which components expect to build (eg, @pluralsight/ps-design-system-normalize).
- `core` is not a peerDependency at this point and should be included as a `dependencies` entry where needed.
- CSS-in-JS was chosen (as opposed to CSS stylesheets) so the install story was simpler, not requiring bundler configuration.
- CSS-in-JS was chosen (as opposed to vanilla inline styles) in order to support styles that inline styles don't (eg, media queries, pseudo selectors and @keyframe animations).
- `devDependencies` definitely shouldn't be included in the `dist/` output of bundles.  If it is, as it seems it might, we need to figure out how to build our packages to exclude that.
- I like your analogy of cars and legos. I'm also a Lego-preferring kind of UI dev. We are also, however, trying to service traditionally fullstack devs who have less UI experience. To this end, we have packaged some things up into larger components.  Some times we may have gone too large and complex.  And our user base is changing constantly.  We need to be more nimble to discover how well the DS is being received and utilized. Your feedback continues to be helpful in this regard.

Thanks for your time and insight!

**Comment by jaketrent** [comment]
No plans to act on fundamental changes here currently. Will add revisit label as we consider any big-picture changes in the future.
