### ISSUE TITLE
No Access to Design System on Figma?

### ISSUE THREAD

**Issue by dorukde** [pluralsight/design-system#1116]
### Steps to repro

1. https://design-system.pluralsight.com/design-assets
None of the assets were accessible with a Figma account. 

### Expected
Accessible links for Figma design system libraries. I received "not found" error.

**Comment by jaketrent** [comment]
Triage: These assets are apparently not public at this point.  Will remove this page.

**Comment by anindha** [comment]
@jaketrent I am confused. What is the point of having an open design system if you aren't going to make the assets public?

**Comment by sweeting** [comment]
@anindha @jaketrent Since moving our design assets to Figma we're unable to change the permissions on the Figma library files to both allow the public to view them and have them enabled by default for our teams internally. When I set them to "Anyone with the link can view" it disables them for all of our internal teams. When I set them to be enabled by default for all teams, it forces me to switch the permissions back to "Anyone at Pluralsight can view". It may be a bug so I'll report it to Figma. 

We may publish them to Figma Community in the future and link to the files there from the design system site. Sorry for the inconvenience. We would like to make everything public. 

For now, we'll just remove the links to the design assets since they are only accessible internally.

**Comment by jaketrent** [comment]
^ @sweeting , thanks for the context.

**Comment by anindha** [comment]
@sweeting Thanks for the clarification. Would it be possible to take a snapshot and share that publicly while still maintaining your internal permissions for the master file? 

I started a project this week and would like to use the design system since I think the design at Pluralsight is outstanding.

**Comment by anindha** [comment]
@danethurber would it be possible to keep this open? It would be good to hear if my suggestion of creating a snapshot that is made public is viable.
