### ISSUE TITLE
action-menu: animate remaining transitions

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#112]
### Desired behavior

Animate as menus EXIT (reverse or ENTER), and animate item background (fade)

### Today's behavior

Slick animation of menus appearing, but no transition when disappearing. Menu item background doesn't currently animate.

### The Value Add

✨ Sparkle ✨

### The Tradeoffs

None

**Comment by jaketrent** [comment]
Additional context:

Animating exits in react are a lot more complicated than animating entrances.  The entrance animation can be done with pure css transitions -- it's one time, it happens when the element is mounted, it's managed by the browser in css.  On exit, however, React removes the element from the dom immediately, leaving no opportunity to animate. There are libraries that work around this and provide extra hooks to handle this, such as react-motion.  

But as a tradeoff, they will add complexity and library weight.

**Comment by dborodyansky** [comment]
@jaketrent, makes sense, and not a tradeoff we want to immediately invest in then (menu animation). How about the item background color transition?

**Comment by jaketrent** [comment]
@dborodyansky a background color transition on entry seems fine to me.  I'm still a bit unclear on the desired behavior on that though.  Please elaborate.

**Comment by dborodyansky** [comment]
@jaketrent, this line on the menu item button achieves the desired behavior: `transition: background 150ms;`

**Comment by jaketrent** [comment]
Our decision: no animate on exit for now; do the bg transition
