### ISSUE TITLE
Card: ellipsis on long names is added after delay

### ISSUE THREAD

**Issue by KaidenR** [pluralsight/design-system#123]
### Expected behavior
The ellipsis should be added immediately or the title should not render until it has been ellipsis-ed

### Actual behavior
The card renders without an ellipsis, then after a delay (< 1 second), the ellipsis is added. This looks bad.

You can see it in the design system demo page: 
http://design-system.pluralsight.com/components/card/#title 
Look at the title of the second card in that section and refresh the page 

### Steps to repro

1. Load a card that has a long name that needs an ellipsis
2. Notice that the ellipsis is added slightly after the card's initial render

### Related packages

- card@6.0.6

### Environment

- OS - MacOS 10.12.6
- Browser version - Chrome v61.0.3163.100

**Comment by jaketrent** [comment]
maybe: experiment with react-truncate -- see if can increase speed

maybe: experiment with not rendering text until sizing in-browser is complete.

who knows: maybe we can't do too much since this code has to do sizing calcs and run after paint

**Comment by jaketrent** [comment]
I don't know exactly where to go with this.  It would need some experimentation around a tricky issue.  I'm really relying on react-truncate at this point and letting it do its thing to get us line clamping.  

I'm going to close for now because the issue has been around without any treatment for months.  

If there is continued/additional pain around this, please note it in the comments or in slack, and we can look closer at it.
