### ISSUE TITLE
nav: show product switcher in reference design

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1567]
Show the product switcher icon and menu in the nav reference design

**Comment by jaketrent** [comment]
@sweeting Is this a design task for you, or is the reference done and now it should merely be added to the docs?  I see the product switcher in the reference design area in figma, but it's not jivin' with what I was expecting, so I thought I'd clarify: Namely, we talked the other day as if this wasn't done, but what's there has been there for some time, I think. Also, we talked about using placeholders instead of the concrete products and branding so-as to reinforce that we don't own it. We didn't precisely decide that was going to be the approach; it was just a part of the conversation. Anyway, please clarify.

**Comment by sweeting** [comment]
Design is ready: https://www.figma.com/file/YsTklBecdddy9RZ3HXddIseD/PSDS-Web-Components?node-id=12383%3A1524

**Comment by jaketrent** [comment]
@sweeting I'd love to help with this if it's ready for me.  I'm not sure if it's a design task or a "go change the docs" task at this point.

**Comment by jaketrent** [comment]
I think we're done here.  Really not sure what else to do. Reopen if you do know what's left.
