### ISSUE TITLE
button: Allow Button to have user provided custom markup 

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#248]
## Enhancement Request

I would like to be able to provide an alternate element for the `Button` to render with so that I can integrate with 3rd party routing libraries - like `react-router` - and use their `Link` element, but keep the `Button` styles.

Prior art:
- https://material-ui.com/demos/buttons/#third-party-routing-library
- http://elemental-ui.com/buttons#usage

In both of these examples, an additional `component` prop is present on the `Button` that allows the consumer to specify what component should ultimately be rendered

### Desired behavior

I'd like to be able to leverage the `Button` styles, but for arbitrary components that I provide.

### Today's behavior

Trying to use a `Link` from react-router end up generating "awkward" HTML (potentially not semantically correct). 

```jsx
<Button>
  <Link>My Text</Link>
</Button>
```

will result in:

```html
<button>
  <a href="...">My Text</a>
</button>
```

### The Value Add

This would make the `Button` component more flexible to help integration with 3rd party libraries

### The Tradeoffs

I'm not sure? This seems to be a fairly common practice I've encountered among components libraries (regardless of framework).

**Comment by jaketrent** [comment]
Triaged: tech discovery needed on what's possible and desirable in api.

**Comment by jaketrent** [comment]
Amazing how many opinions people have on how to solve this:
https://stackoverflow.com/questions/42463263/wrapping-a-react-router-link-in-an-html-button

Amazing because react-router Link provides the `a` semantics, which I think it shouldn't (eg, as in `next/link` https://github.com/zeit/next.js/#with-link)

Still thinking about what the best ways to work with this are.

**Comment by jaketrent** [comment]
The HoCs like `withRouter` are the envisioned solution for custom links from the react-router creators: https://github.com/ReactTraining/react-router/issues/1176#issuecomment-113188481

**Comment by jaketrent** [comment]
I'm thinking right now... `Button` css is already available (as you know from your Vue work).

You could do the same thing in react if you really wanted to use the `react-router-dom` `Link` component:

```
import buttonCss from '@pluralsight/ps-design-system-button/css'
import { Link } from 'react-router-dom'

const CustomLink = props => <Link {...props} style={buttonCss['.psds-button']} />
```

If you're in react, it does seem more natural to use the DS component api.  But once you created your `CustomLink` component wrapper in order to get your arbitrary markup/semantics/component, you'd be back in that business.

It feels odd to open the semantics of button up to any/everything.  Beyond `a` and `button`, there's really not another tagName that makes sense to me in the dom at this point.

I think that this desire for applying button looks to arbitrary general components really is to allow react-router Link specifically, as is also stated above.  For that problem, I'm leaning towards not working against the design of react-router, and using their suggested design for custom links (ie, HoCs. above ^).  Though they have very little in their docs about how to do this well.  It might be worth adding a very specific example in the button docs on the ref site for devs using react-router.

**Comment by willsoto** [comment]
Thanks for continuing to look into this!

My biggest concern with most(?) of the solutions provided in the [SO post](https://stackoverflow.com/questions/42463263/wrapping-a-react-router-link-in-an-html-button) is the fact that they aren't semantically correct. `button > a` actually doesn't work in FF (which is how it should be as you pointed out in https://github.com/pluralsight/design-system/issues/376#issuecomment-445360453). Having `a > button` is technically valid markup, but I think it could be simpler if you just had `a` with some CSS classes that made it look like a button.

In terms of bootstrap: `a.btn.btn-primary` looks exactly like `button.btn.btn-primary` which feels like a pretty clean API to me.

---

In terms of creating a custom HOC that leverages "private styles" from the `button` - I am not sure I am totally crazy about that idea.

_As a consumer:_ using the DS in its native language (React) I have to reach into private APIs in order to get the styles I want.

_As an API provider:_ I wouldn't feel comfortable with letting people leverage my internal styles like that for what I would consider a "common" use case. 

That is, of course, totally my opinion.

---

If I can ask, is there anything in particular you don't like about how [two major](https://material-ui.com/demos/buttons/#third-party-routing-library) [design systems](http://elemental-ui.com/buttons#usage) handle this situation? I personally find it to be a very clean solution to this problem.

**Comment by jaketrent** [comment]
And thanks for continuing to help weigh the tradeoffs...

Agreed, I want us to end up with a semantically correct solution.

The styles for DS components are *not* private.  They have been exposed as a public api for use-cases such as your other Vue-DS tie-in's specifically.  We try to treat them as such, which is admittedly challenging.

I feel like our DS is different from the material and elemental design systems in that we are specifically trying to address what we believe Pluralsight needs and how it should be supported, where-as they are general, open source, "take me and do whatever you want" with them.  We don't need to try and support as much.  

I don't love what react-router has done with their Link, as I've said, and I'm not wanting to shape our solutions around this direction chosen by the other library, especially when solutions are provided by this library already to accomplish what is desired (eg, `withRouter`).

The `component` prop for material's button is probably just fine for adjusting button semantics.  I just need to try it out to see if it feels right.

**Comment by jaketrent** [comment]
I don't use react-router much, so I should have done this a lot sooner, but I spun it up and made a react-router `Link` look just like a `@pluralsight/ps-design-system-button`:

```
import Button from "@pluralsight/ps-design-system-button/react"
import { Link, withRouter } from "react-router-dom"
const CustomLink = withRouter(props => (
  <Button
    {...props}
    onClick={evt => {
      evt.preventDefault();
      props.onClick && props.onClick(evt);
      props.history.push(props.to);
    }}
    href={props.to}
  />
))

// ... called like:
<CustomLink to="/other">React-router Link as DS button</CustomLink>
<Button href="https://duckduckgo.com">Anchor DS button</Button>
```

That look the same:

screenshot

And both have the expected semantic markup:

screenshot

**Comment by willsoto** [comment]
Would you be able to support a regular anchor tag using the above methods?

**Comment by willsoto** [comment]
> I feel like our DS is different from the material and elemental design systems in that we are specifically trying to address what we believe Pluralsight needs and how it should be supported, where-as they are general, open source, "take me and do whatever you want" with them. We don't need to try and support as much.

While I can kind of see this, I don't necessarily agree with it fully. There is a non-zero overlap between what our DS solves specifically and what _any_ design system solves. I think this is one of those use cases. So looking at prior-art can be useful since the needs of PS ultimately overlap with the broader needs of anyone designing a modern web app.

---

It's good to know that the stated solution for react-router Link works with the button, but I can't help but think it shouldn't require a user-land solution. While I do understand that this makes the DS slightly more _complex_ I don't think it makes it more _complicated_ and the benefits of this API outweigh the potential costs in my opinion. It allows for a more flexible component that doesn't require users to pass around a wrapper around _two_ components. The [implementation for material-ui](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/ButtonBase/ButtonBase.js#L273-L288) is not that many lines (as best as I can tell). 

This same API could be used to solve #376 (imo) by allowing users to pass custom components to the `Tab.ListItem` components. 

---

If you are open to it, I'd be willing to give implementing this a shot since I believe very strongly in it.

**Comment by jaketrent** [comment]
There is definitely overlap between the two design systems.  Yes, I want to learn from others' successes.  I don't want to do things just because they've been done with success elsewhere.  If copying their successful idea feels like the best option, we shouldn't shy away from it.  I'm just not convinced it is, and so I'm not ready to jump on the bandwagon there.

Solutions to deal with react-router seem to fit in userland very well.  The Design System has no affiliation with react-router.  Inasmuch as our users use react-router, we should enable them to be compatible with us, but it's looking like we don't need to do anything new in this case.  React-router already envisioned how their tools should be used in this case and created a solution which seems simple and easy enough for their users.

If you'd like to work on this, I have no problem with it.  It might be fun to explore.  As you can tell, I'm not super hot on the material-ui solution, and I will feel worse after you've created the PR for implementing it if we decide not to go that direction, which is my current leaning.  But, if after those caveats you're still enthusiastic to work on it, I'd be happy to look at what can be created and perhaps would find something compelling about seeing concrete code in a branch of our code in order to make a better comparison.  

Thanks for sharing your perspective with me in this thread thusfar.  Enjoy the weekend, and we can talk more next week.

**Comment by jaketrent** [comment]
Without adding to the Button component, we've documented a simple method where react-router integration is accomplished with today's DS Button.

https://design-system.pluralsight.com/components/button/#with-react-router

For now, we'll close this issue and not move on the new API.  If new compelling reasons for allowing custom tagNames appears in the future, we can relook at that potential pathway.

Thanks for your thoughts on this, Will.
