### ISSUE TITLE
TextInput: should not remove outline on focus (accessibility)

### ISSUE THREAD

**Issue by ShaynaCummings** [pluralsight/design-system#267]
### Expected behavior
When using the textInput component and tabbing through, the user should see an outline around the textInput when it is in focus.

### Actual behavior
There is no outline when the focus is on the input. This is due to the following:
https://github.com/pluralsight/design-system/blob/master/packages/textinput/src/css/index.js#L35

### Steps to repro

When tabbing through a page with a textInput, notice that there is no outline on focus:
![tabbing](https://user-images.githubusercontent.com/6797841/46305533-bc91f280-c57f-11e8-9b5f-e2483a0373e9.gif)

### Related packages

- ps-design-system-textinput @ 0.4.0 

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

**Comment by jaketrent** [comment]
The TextInput does not, in fact, remove the focus indicator.  It creates its own custom one.

In fact, all of the Form components do.  Check them out here.  https://design-system.pluralsight.com/components/form/#form-controls

The current implementation, however, may require that you create a new css stacking context in order to make it visible.  This is because the border is created using a negative z-index.

This is one way to create a new stacking context:  On the parent, use the styles:

```css
.parent {
  position: relative;
  z-index: 1;
}
```

I've been trying to think of a good place in the docs to put this tidbit.  I would also be interested in anyone who can think of a solid way to recreate the current custom focus indicator w/o needing this at all.  I'm open to ideas.  Closing this issue for now.

**Comment by KaidenR** [comment]
@ShaynaCummings Just a heads up that this issue should be fixed now that PR #284 is merged. You don't need to set up your own stacking context outside the textInput anymore.
