### ISSUE TITLE
tab: responsive / scrollable tab group support

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#287]
### Desired behavior

(Via BlueShell) 

Support for horizontally scrolling tabs at narrow viewports.

![image](https://user-images.githubusercontent.com/3674406/47038888-6f914d00-d137-11e8-9b38-d70447067791.png)

### Today's behavior

Wrapping + overflow hidden

![image](https://user-images.githubusercontent.com/3674406/47038912-7e77ff80-d137-11e8-8ca9-e291ae9e246a.png)

### The Value Add

Improved ux affordance. Responsive design advocacy.

### The Tradeoffs

Complexity around mouse interaction?

**Comment by jaketrent** [comment]
Status: Investigate ref material for accessibilty concern.

**Comment by dborodyansky** [comment]
Revisiting accessibility and non-touch interaction for scrollable tabs, I'd like to propose the inclusion of L/R scroll buttons for desktop experiences, based on viewport width. Here is an implementation example for reference: https://material-ui.com/demos/tabs/#automatic-scroll-buttons

Proposed design:
https://www.figma.com/file/ffRCsJ1l6UFcXgAKNS1zprvm/Responsive-tabs?node-id=0%3A1

@jaketrent @danethurber

**Comment by jaketrent** [comment]
triage: need design review

**Comment by jaketrent** [comment]
## Design Review

- What about "don't put more than 3 tabs" in this UI advice?  (considering best ux, tricky impl and opp cost)
- No wrap? (always one row?)
- Overflow buttons based on container width (not viewport as mentioned above ^^), right?
- No buttons mobile in viz design?
- What is intended when pressing a scroll button?
- What is intended when keyboard/arrow nav'ing "offscreen"?
- What is intended on mount when active item is "offscreen"?
- Tab order of overflow buttons?  First impression, since tab switch is arrow based, not included in tab order.
- Hover state for overflow button?
- Light theme viz design for overflow buttons?

Tech discovery:

- [Possible script to detect touch device](https://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript/4819886#4819886) to remove overflow arrow buttons
- Detecting "offscreen".  Find focus/active/intended item, test position (on what?? w/in parent would be best... how?), test parent/container width, compare
- Scroll action - move track the length remaining offscreen track unless longer than container width, then 1 container width

**Comment by jaketrent** [comment]
- +3 tabs - good advice; still have overflow cases
- tab labels - 300px max on item width, then wrap
- design experiment - overflow button bg, hover state, light theme
- mobile buttons - yes, always
- keyboard arrow - page 1 at a time
- overflow button click - full list width (page) at a time
- on mount, offscreen comes onscreen at far right
- no swipe/scroll to get rid of native scrollbar; paging solution in overflow button press only
