### ISSUE TITLE
tab: Anchors inside Tab.ListItem don't work in Firefox

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#376]
_This is kinda both a bug and a feature request, since I think implementing the feature will fix the bug._

### Expected behavior

Using an anchor for a tab works as expected.

### Actual behavior

Anchor tags inside of `button` don't work in Firefox (See [this SO post](https://stackoverflow.com/a/16280685))

[Source](https://github.com/ps-dev/Projects-UI/blob/c0ad605a1785717c4720c92eb8d1bfcf26f29650/src/detail/tabs/index.js#L112-L116)
[Link to GIF](https://drive.google.com/open?id=1_oUunjw5JpCzClYVAYDF6FNSl40zbVFD) (It's big, sorry). You can see an example of the correct behavior in Chrome (URL changes when tab is clicked so users don't lose their position)

### Steps to repro

1. Navigate to any Project detail page (eg [here](https://app.pluralsight.com/projects/add-features-with-forms-to-a-vue-js-reading-list-application). 
2. Click around on tabs in Chrome
3. Click around on tabs in Firefox

### Related packages

- button@10.8.3 (maybe? Would have to check implementation of Tab)

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v71 (works) Firefox v63 (doesn't work)

### Desired behavior

Add ability to replace `Tab.ListItem` with custom markup

### Today's behavior

`Tab.ListItem` does not allow custom markup

### The Value Add

Related to #248. Similar value add

### The Tradeoffs

Slightly more complex implementation? But ultimately worth it in my opinion.

**Comment by willsoto** [comment]
Just saw #356 - sorry for the dupe...it's kinda related I think, but it would be ideal if we could pass a custom component imo (since things like React Router use `Link` and not `href`)

**Comment by jaketrent** [comment]
Funny, perhaps the same day this was filed here, almost same issue was filed on react-router site: https://github.com/ReactTraining/react-router/issues/6499

He created the same kind of markup that's in the source link in this issue above.

**Comment by jaketrent** [comment]
With the completion of #356, `href` are now support on `Tab.ListItem`, making semantic markup possible for links from tabs.  

I've also verified that react-router has a story that satisfies its own routing needs while keeping the semantic markup.  This can be accomplished using its [`withRouter` HoC](https://reacttraining.com/react-router/web/api/withRouter), as in:

```js
import { withRouter } from "react-router-dom"
import Tab from "@pluralsight/ps-design-system-tab/react"

const CustomListItem = withRouter(props => (
  <Tab.ListItem
    {...props}
    onClick={evt => {
      evt.preventDefault()
      props.onClick && props.onClick(evt)
      props.history.push(props.to)
    }}
    href={props.to}
  />
))

<Tab.List>
  <Tab.ListItem id="menu2" href="/other">Other link</Tab.ListItem>
  <CustomListItem id="menu3" to="/other">React-router Link</CustomListItem>
</Tab.List>
```

It looks and behaves the same as the vanilla `Tab.ListItem` with `href`.  Please use this approach for getting valid markup instead of nesting the `Link` tag, and you should be set in Firefox as well as the other browsers.

Closing for now.  Please re-open if this turns out insufficient to support your use case.
