### ISSUE TITLE
tooltip: add support for light theme

### ISSUE THREAD

**Issue by dmcquayps** [pluralsight/design-system#396]
### Desired behavior

I think we should make the entire tooltip dark when used in Light Theme. If for some reason we don't want to do that, the tail at least needs more contrast when placed on the top.

### Today's behavior

<img width="386" alt="screen shot 2018-12-13 at 9 49 28 am" src="https://user-images.githubusercontent.com/29869590/49954510-dcb62a00-febd-11e8-9e4e-bd984b430671.png">

**Comment by dborodyansky** [comment]
We considered a dark tooltip in the past, but decided against it in favor of the light one working across themes. Clearly there is some deficiency with the shadow though, but I'd like to update it in total, outside of theming.

Two issues here I think:

1) Change tooltip box-shadow value `box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.5);
... in fact this change is best applied to `action-menu` as well, because they are the same (should we make a default shadow var via `core`?)
2) Explore containing the tail with the outer div when applying the box-shadow, and not independently. Related to #397

**Comment by dmcquayps** [comment]
Update: For guides to use this, we need to control the background color. We want a dark background. We spoke with Dmitry about this and got his agreement, but thought it should be documented here. I believe the plan is to give us ability to override some CSS, but Dmitry said he was going to do a little digging around to see if enough teams needed this that we should just have a configuration option to choose dark background.

**Comment by dmcquayps** [comment]
Also, I was told we should be using the Dialog component for our use case, not the Tooltip. Therefore all of this applies to Dialog now, not Tooltip.
