### ISSUE TITLE
dialog: UI components flickering in popup

### ISSUE THREAD

**Issue by eugene-kovaljov** [pluralsight/design-system#473]
## Bug
While using the Mac screen to represent the app feature we are observing flickering of entire popup. 

Steps: 
Create a React portal
Put there a dialog component
Put the dropdown/switch components into the popup container
Toggle it. 
Observe the flashing (see attached video. rename it to .mov-format)
[flashing modal.pdf](https://github.com/pluralsight/design-system/files/2905308/flashing.modal.pdf)

For Switch component setting the transition none helped.

**Comment by jaketrent** [comment]
Hi @eugene-kovaljov ,

Thanks for filing this so we could help you take a look.

I looked at your video, and I can see the blinking there.

I then tried to repro this in code.  The code is here: https://github.com/jaketrent/test-dialog-portal

I could not get the blinking to happen.  I do not believe that it is an inherent problem with the Dialog or Switch.  

But, obviously the problem is happening to you.  What combination of things is causing that to happen?  I'm not sure, but my first guess is that you're storing state somewhere higher in the tree, when you click one of the switches, it's adjusting the state, that state trickles down via props to some components. 
 It's probably redrawing the component that calls `createPortal`.  Else, I'm not sure why you'd have the blink.  

Of course there might be something else at play.   I haven't seen the code.

What should we do from here, do you think?  Do you have thoughts on the next debugging step?

**Comment by jaketrent** [comment]
btw, the relevant code is here: https://github.com/jaketrent/test-dialog-portal/blob/master/src/App.js

**Comment by jaketrent** [comment]
I tried moving the state up to see if I could get the blink.  I still didn't see it.

Diff: https://github.com/jaketrent/test-dialog-portal/compare/9890dae1f8ef31fd65e7623853d1f2f04d1a9282..16d152908313d689d3ed508f08995c4a7a9ae9ad
