### ISSUE TITLE
Carousel: Context menus cut off by carousel container

### ISSUE THREAD

**Issue by nttibbetts** [pluralsight/design-system#593]
### Expected behavior
When opening an action menu on a card in a carousel, the menu should not be hidden by the carousel container

### Actual behavior
The action menu is cut off at the edges of the carousel container

![Screen Shot 2019-07-26 at 10 16 09 AM](https://user-images.githubusercontent.com/1699510/61969090-ae4a1280-afa7-11e9-922f-dec2d1865d13.png)

We were just experimenting with replacing our carousel with the design system carousel but didn't commit the changes. If necessary we could commit this to a branch, but it'd likely be easier to mock it up as it's all design system components.

### Steps to repro

1. Add a card component with an action menu in its action bar with about 5 items to a carousel
2. Show the action menu

### Related packages

- carousel@1.1.1
- card@9.0.7
- actionmenu@4.1.7

### Environment

- OS - OSX 10.14.5
- Browser version - Chrome v75

**Comment by jaketrent** [comment]
Triage: We can attempt the solution below.  React.createPortal is also a great solution for this.

Possible solution: thinking that overflow:hidden needed for transition time only.

**Comment by nttibbetts** [comment]
Doing `overflow: hidden` only during transition was the solution we landed on for our custom built carousel component. The only downside was it was a touch tricky to nail down the positioning logic during transitioning vs after transitioning.

This was after considering using React Portals but this created the problem of needing to include a significant amount more of ReactDOM and nearly tripled our bundle size (we have a fairly basic experience so not much code/dependencies to start with). There was also the problem of needing to do a bit of CSS math to position it correctly, but @danethurber has pointed out the Position component that might solve that problem if you went with a portal based solution.

**Comment by popthestack** [comment]
We had the same problem with menus getting cut off. I tried `React.createPortal` and was able to get the menu working, but it broke accessibility. For example, using the tab key to navigate worked until needing to dismiss the menu. Once dismissed the focus was at the bottom of the page where the portal element had been. I didn't look into any solutions, but instead switched to removing `overflow: hidden` when a menu is activated and putting it back when it is unmounted.

One problem that came up when removing `overflow: hidden` was that it added a horizontal scrollbar to the page because the empty `li[hidden]` elements have a width. I worked around this by making the `li[hidden]` elements 1px wide while the menu is open. It worked great except when paginating. I fixed that by using this crazy selector in the carousel `li:not([hidden]) ~ li[hidden]` to only set `li[hidden]` elements to 1px _if_ they come after the active list element. I'm happy to explain more if that makes no sense.

**Comment by nttibbetts** [comment]
That's an interest set of workarounds, thanks for sharing them! :+1: I also appreciate pointing out the accessibility concern when using a React Portal to solve this issue as I hadn't actually considered that.

It's worth noting you'd likely need an identical `li[hidden] ~ li:not([hidden])` select for elements before the current page when not on the first page.

If we were under a bigger push to move to the Design System Carousel, I'd definitely use those, but I generally prefer not messing too much with the CSS of any of the components as it creates an eventual maintenance task when moving from version to version of a component.

**Comment by popthestack** [comment]
We have our changes up on staging if you want to see how the carousels work with the menus.
