### ISSUE TITLE
Note: Should display new lines

### ISSUE THREAD

**Issue by getschomp** [pluralsight/design-system#660]
#  Bug

### Expected behavior

Then the user uses a text input to store text across multiple lines and it should render in the note component with new lines.  

### Actual behavior

example:
```
Hello 
World
```
is rendered as
```
Hello World
```

We have a fix here:

https://github.com/ps-dev/assessment-tools/pull/452/files

but we thought that css might belong in the component.

### Related packages

- note@2.0.3

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v76

**Comment by getschomp** [comment]
<img width="636" alt="Screen Shot 2019-09-09 at 10 39 11 AM" src="https://user-images.githubusercontent.com/5835824/64540525-5d3f7500-d2ee-11e9-8ee8-c2eb985cbd27.png">
<img width="645" alt="Screen Shot 2019-09-09 at 10 38 55 AM" src="https://user-images.githubusercontent.com/5835824/64540537-60d2fc00-d2ee-11e9-80a4-7ee64488cba2.png">

**Comment by jaketrent** [comment]
Team triage:

Rich text formatting is quite variable (eg, plain text with newlines, html or markdown).  The Note expects this and is flexible to take any node.  You can put anything renderable there.  

To keep your data format (plain text with newlines) and render multilines as you want, your current solution is great (ie, using className on Note).  You could also just pass a `div` with that className to the `message` prop.

Another recommendation from the team is to consider rending html `<p>` instead of just using the newlines for better semantics on this structure.

Closing with nothing to do in DS here.  Please keep relying on your current solution.  Please continue to engage with more context if you feel our reasoning in response is flawed.  Thanks!
