### ISSUE TITLE
dialog: responsive

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#726]
Make dialog responsive on small screens allowing overflowing content to scroll while keeping actions visible.

Design
https://www.figma.com/file/YsTklBecdddy9RZ3HXddIseD/?node-id=10241%3A0

**Comment by tjmabey** [comment]
this would be really nice for something we are working at right now

**Comment by jaketrent** [comment]
@sweeting, since some are using Dialog as a tooltip, should we only do this maximization if the `modal` prop is set, I'd guess?

**Comment by sweeting** [comment]
@jaketrent I would really like to remove the things that make `Dialog` usable as both a modal dialog and a "mega tooltip" and create new [`Popover`](https://www.figma.com/file/YsTklBecdddy9RZ3HXddIseD/?node-id=11492%3A282) component to accommodate the "mega tooltip" use cases.

**Comment by jaketrent** [comment]
@sweeting Ok, great.  What I'm hearing is that you would like to not doing the dialog responsive thing right now until we separate out what Dialog is vs other components like it.  Works for me.

To this end, if you think we're working this in the short term, would you please prepare a visual and verbal spec for Dialog and the other components you see, please?  Outlining:

- How are they different?  Why is their separation important?  What can each do that they others can't?
- What is the specific purpose of each, with common use cases?

Once we have that knowledge clearly communicable, I'd like to do a team design review of that so that we can all agree on the approach.

**Comment by sweeting** [comment]
@jaketrent Done. I've added details about how Popover is different than Dialog to the DS Requests spreadsheet.

**Comment by jaketrent** [comment]
There were enough design decision to make that it feels better to leave this until we look at the popover ecosystem.  That will come after some user research questions are answered and we're ready for that priority. Cards will be (re)made.
