### ISSUE TITLE
Tab now working in default theme and dark theme.

### ISSUE THREAD

**Issue by ripley** [pluralsight/design-system#830]
See https://codesandbox.io/s/unruffled-bash-poevi

The tab's titles are not visible in dark theme and default theme.

**Comment by jaketrent** [comment]
Hey @ripley , I think you're reporting a bug.  

As far as I can tell, Tab is exhibited expected behavior.  Dark theme assumes a dark background.  

Here's a fork of your sandbox to show this in action. https://codesandbox.io/s/delicate-glitter-ocz1z

Closing for now.  Please let me know if you have other concerns.
