### ISSUE TITLE
Tooltip copies props of wrapped element

### ISSUE THREAD

**Issue by benallred** [pluralsight/design-system#893]
https://github.com/pluralsight/design-system/blob/65ffbfc430f20525c2b512593e5f11069a890db3/packages/tooltip/src/react/index.js#L77

Any reason this doesn't allow another element?

The XY problem we're trying to solve here is, the element we're wrapping in `Above` has `color:#fff`. (https://github.com/ps-dev/plan-analytics/blob/skills/client/lib/reports/all-skills/index.tsx#L480) That style is being applied to the tooltip for some reason (I'm having trouble finding in the `Tooltip` code where/why that might be happening (maybe `filterReactProps`?)) so the text in the tooltip is not visible. So we're wrapping our tooltip text in a `p` tag with `color:#000`. (Putting `style` directly on `Tooltip` is being overridden.)

I see other issues where the response is to use a dialog, but this is semantically a tooltip and is non-actionable.

We don't need the `p` element if our styles don't get copied to the tooltip. Any suggestions?

cc @twclark0

**Comment by jaketrent** [comment]
Tooltip's intended UI means that it only has strings.

For UI that can hover and be positioned next to things, there is Dialog, which has a few differences and may work for your intended UI. https://design-system.pluralsight.com/components/dialog

Though from the link to your src, it does look like you only want a string, so the intended UI likely matches what Tooltip intends to support.

Aaaanyway, as far as why your app styling is affecting the Tooltip styling, I'm less sure.  Tooltip does set its own `color`, so I assume you can see that in browser devtools.  I assume that you can also see what's overriding it.  It's possible that the issue is selector specificity, order, or importance -- the usual CSS cascade issues.  

We might need to pair to get to the bottom of it.  Not sure how long you've spent on this problem along these lines of thinking.

**Comment by benallred** [comment]
DevTools shows that the inline style of our `p` tag inside of `Above` is getting applied to the `div` that holds the text inside `Tooltip`.

```
    const legendTitlePElement = (
      <p
        style={
          activeLegendTitle === props.name
            ? {
                color: '#fff',
                borderLeftStyle: 'solid',
                borderLeftColor: '#fff'
              }
            : {}
        }
        className={css.barChartLegend}
        key={props.index}
        onMouseOver={() => {
          updateLegendTitle(props.name)
          updateShowTip(true)
        }}
        onMouseOut={() => updateShowTip(false)}
      >
        {props.name}
      </p>
    )

    const tooltip = (
      <Tooltip tailPosition={Tooltip.tailPositions.bottomCenter}>
        <p style={{ color: '#000' }}>{props.name}</p>
      </Tooltip>
    )

    return (
      <Above ref={legendTitleRef} show={tooltip} when={useTip && showTip}>
        {legendTitlePElement}
      </Above>
    )
```

**Comment by benallred** [comment]
Seems like a bug.

https://codesandbox.io/s/black-water-8ceox
