### ISSUE TITLE
site: add doc for currentColor to Icon page

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#978]
reported here: https://pluralsight.slack.com/archives/C70HPSJPP/p1587136196052900

**Comment by jaketrent** [comment]
Triage: stay with currentColor as default. Add a doc example on the Icon page for how to do that.

The back and forth...

Jake:
At first read, I was also thinking that it seems true enough, the Icon must react to Theme. But it does not, at least independently.  When Icon appears in other components, we make it react with the rest of that component to Theme.  But by itself (and just confirmed in src), Icon only reacts via fill: currentColor.  Or you can set it with a color prop directly.  If you’re using Icon inside of a custom component, I’d make that custom component react with useTheme (from Theme pkg) and then set the color there.  That should make Icon react as desired.

https://codesandbox.io/s/psds-example-template-f2sjh?file=/src/App.js

Will:
Thanks. I feel like I understand from a technical perspective why this might have to work like this but from a consumer perspective it does feel like a bug since other components do respond to the theme.

Jake:
Yeah, the sentence “Icon doesn’t respond to theme” gives me that same feeling.
Thinking about it, how would the Icon respond to theme?
It doesn’t have a “default” color.  It takes the color of its surroundings.  If it did have a default, what would make sense for each theme?  It’s hard to say because an Icon can be anywhere.  For the places we know it’ll be (on a Button, in a DatePicker, etc.), it does respond to Theme.  For all other (custom) places, maybe we could come up with default colors.  But then we’d have to not use currentColor by default, and I’m not sure that’d feel better to consumers either.

Will:
Without totally understanding the problem space, at first glance it feels like you could have some smart defaults:
if (color) {
   // apply custom color
} else if (theme) {
  // pick appropriate color based on theme
}

if currentColor is generally preferable, then I think guidance should be given on how to ensure the icon picks that up. For example, when using an icon next to some Text.P, make sure the icon lives inside the Text element to pick up the color.
